# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=true
android.nonFinalResIds=false

# SDK versions
COMPILE_SDK_VERSION = 34
BUILD_TOOLS_VERSION = 34.0.0
MIN_SDK_VERSION = 24
TARGET_SDK_VERSION = 34

VERSION_CODE = 45
VERSION_NAME = 1.0.0

#library
CONSTRAINT_VERSION = 2.1.4
MULTIDEX_VERSION = 2.0.1
BUTTERKNIFE_VERSION = 10.2.3
GREEN_DAO_VERSION = 3.3.0
EVENT_BUS_VERSION = 3.3.1
RXJAVA_VERSION = 1.3.8
RXANDROID_VERSION = 1.2.1
RETROFIT_VERSION = 2.9.0
DAGGER_VERSION = 2.51.1
OKHTTP_VERSION = 3.12.13
GLIDE_VERSION = 4.16.0
ROUNDED_IMAGEVIEW_VERSION = 2.3.0
CIRCLE_IMAGEVIEW_VERSION = 3.1.0
TOASTY_VERSION = 1.5.0
MATERIAL_ABOUT_VERSION = 2.4.2
MATERIAL_DIALOG_VERSION = 0.9.6.0
LOGGER_VERSION = 2.2.0
STICKY_HEAD_VERSION = 0.4.3
JSOUP_VERSION = 1.17.2
COROUTINES_VERSION = 1.3.7
MATERIAL_VERSION = 1.12.0
CORE_VERSION = 1.13.1
APPCOMPAT_VERSION = 1.7.0
RECYCLERVIEW_VERSION = 1.3.2
PREFERENCE_VERSION = 1.2.1
BROWSER_VERSION = 1.8.0
MARKWON_VERSION = 4.6.2