apply plugin: 'com.android.library'

android {
    namespace 'com.thirtydegreesray.dataautoaccess'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 34
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':daautolib-annotations')
}